[package]
name = "rust-ffi-demo-code"
version = "0.1.0"
edition = "2024"

[dependencies]
jni = "0.21.1"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
dashmap = "6.1.0"
[lib]
crate-type = ["cdylib"]